# Generated by Django 5.2.5 on 2026-01-30 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
