# Generated by Django 5.2.7 on 2026-02-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_order_coupon_order_discount_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng')], default='COD', max_length=10),
        ),
    ]
