# Generated by Django 5.2.7 on 2026-02-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng'), ('MOMO', 'Chuyển khoản ví điện tử MoMo'), ('VNPAY', 'Chuyển khoản ví điện tử VNPAY')], default='COD', max_length=10),
        ),
    ]
