# Generated by Django 5.2.7 on 2026-02-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
