# Generated by Django 5.2.7 on 2026-02-02 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_fill_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
