# Generated by Django 5.2.7 on 2026-02-02 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_alter_order_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.IntegerField(default=0, help_text='Số tiền giảm tối đa (0 = không giới hạn)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='Số lượt dùng tối đa (0 = không giới hạn)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
