# Generated by Django 5.2.7 on 2026-02-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0020_alter_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rank_discount",
            field=models.IntegerField(default=0),
        ),
    ]
