# Generated by Django 5.2.5 on 2026-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_order_rank_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Chọn danh mục sản phẩm để áp dụng voucher (để trống nếu áp dụng cho tất cả)', to='shops.category'),
        ),
    ]
