# Generated by Django 5.2.5 on 2026-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0024_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.IntegerField(default=0),
        ),
    ]
