# Generated by Django 5.2.5 on 2026-03-05 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_orderstatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='shops_order_status_9f2a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='shops_order_user_id_9bd431_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid', 'status'], name='shops_order_paid_788e67_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['order', '-changed_at'], name='shops_order_order_i_33035b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['source', '-changed_at'], name='shops_order_source_d52c41_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available'], name='shops_produ_availab_1228a4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'reserved_stock'], name='shops_produ_availab_18632e_idx'),
        ),
    ]
