# Generated by Django 5.2.5 on 2026-03-06 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_order_shops_order_status_9f2a3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', '-created_at'], name='shops_order_user_id_f946a3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='shops_order_changed_329637_idx'),
        ),
    ]
