# Generated by Django 5.2.5 on 2026-03-13 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0031_order_guest_email_order_guest_name_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('EXCHANGE', 'Đổi hàng'), ('RETURN', 'Hoàn trả hàng'), ('REFUND', 'Hoàn tiền')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('COMPLETED', 'Hoàn tất')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('refund_amount', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_requests', to='shops.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_after_sales_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='shops_after_status_90933e_idx'), models.Index(fields=['request_type', '-created_at'], name='shops_after_request_420e6d_idx'), models.Index(fields=['order', '-created_at'], name='shops_after_order_i_7fa167_idx')],
            },
        ),
    ]
