# Generated by Django 5.2.5 on 2026-03-13 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0032_aftersalesrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_STATUS', 'Trạng thái đơn hàng'), ('AFTER_SALES', 'Hậu mãi'), ('VOUCHER', 'Voucher'), ('SYSTEM', 'Hệ thống')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='shops_usern_user_id_c5bf49_idx'), models.Index(fields=['user', '-created_at'], name='shops_usern_user_id_7b28b7_idx'), models.Index(fields=['notification_type', '-created_at'], name='shops_usern_notific_6db2eb_idx')],
            },
        ),
    ]
