# Generated by Django 5.2.5 on 2026-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0033_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng'), ('WALLET', 'Thanh toán bằng ví hoàn trả'), ('MOMO', 'Chuyển khoản ví điện tử MoMo'), ('VNPAY', 'Chuyển khoản ví điện tử VNPAY')], default='COD', max_length=10),
        ),
    ]
