# Generated by Django 5.2.5 on 2026-03-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0034_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='after_sales/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('after_sales_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.aftersalesrequest')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
