# Generated by Django 5.2.7 on 2026-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_latitude_profile_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("Bronze", "🥉 Bronze"),
                    ("Silver", "🥈 Silver"),
                    ("Gold", "🥇 Gold"),
                    ("Platinum", "💎 Platinum"),
                ],
                default="Bronze",
                max_length=20,
            ),
        ),
    ]
