# Generated by Django 5.2.7 on 2026-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("Newbie", "Newbie"),
                    ("Explorer", "Explorer"),
                    ("Shopper", "Shopper"),
                    ("Regular", "Regular"),
                    ("Premium", "Premium"),
                    ("Gold Buyer", "Gold Buyer"),
                    ("Platinum Buyer", "Platinum Buyer"),
                    ("Diamond Buyer", "Diamond Buyer"),
                    ("Elite Buyer", "Elite Buyer"),
                    ("Legend Buyer", "Legend Buyer"),
                ],
                default="Newbie",
                max_length=30,
            ),
        ),
    ]
