# Generated by Django 5.2.5 on 2026-02-27 13:44

import django.core.validators
from django.db import migrations, models


def seed_reward_configs(apps, schema_editor):
    RewardVoucherOption = apps.get_model("users", "RewardVoucherOption")
    MysteryBoxRewardOption = apps.get_model("users", "MysteryBoxRewardOption")

    if not RewardVoucherOption.objects.exists():
        RewardVoucherOption.objects.bulk_create([
            RewardVoucherOption(
                name="Voucher 5%",
                cost_points=500,
                discount=5,
                max_discount=50000,
                valid_days=7,
                active=True,
                sort_order=1,
            ),
            RewardVoucherOption(
                name="Voucher 10%",
                cost_points=1000,
                discount=10,
                max_discount=120000,
                valid_days=7,
                active=True,
                sort_order=2,
            ),
            RewardVoucherOption(
                name="Voucher 15%",
                cost_points=2000,
                discount=15,
                max_discount=250000,
                valid_days=10,
                active=True,
                sort_order=3,
            ),
        ])

    if not MysteryBoxRewardOption.objects.exists():
        MysteryBoxRewardOption.objects.bulk_create([
            MysteryBoxRewardOption(name="+30 điểm", reward_type="POINTS", points_value=30, weight=30, sort_order=1),
            MysteryBoxRewardOption(name="+60 điểm", reward_type="POINTS", points_value=60, weight=20, sort_order=2),
            MysteryBoxRewardOption(name="+120 điểm", reward_type="POINTS", points_value=120, weight=10, sort_order=3),
            MysteryBoxRewardOption(name="+1 lượt chơi", reward_type="PLAYS", plays_value=1, weight=15, sort_order=4),
            MysteryBoxRewardOption(name="+2 lượt chơi", reward_type="PLAYS", plays_value=2, weight=8, sort_order=5),
            MysteryBoxRewardOption(
                name="Voucher 5%",
                reward_type="VOUCHER",
                voucher_discount=5,
                voucher_max_discount=30000,
                voucher_valid_days=5,
                weight=5,
                sort_order=6,
            ),
            MysteryBoxRewardOption(name="Chúc bạn may mắn lần sau", reward_type="EMPTY", weight=12, sort_order=7),
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mysteryboxhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBoxRewardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reward_type', models.CharField(choices=[('POINTS', 'Cong diem'), ('PLAYS', 'Cong luot choi'), ('VOUCHER', 'Voucher'), ('EMPTY', 'Khong trung')], max_length=20)),
                ('points_value', models.PositiveIntegerField(default=0)),
                ('plays_value', models.PositiveIntegerField(default=0)),
                ('voucher_discount', models.PositiveSmallIntegerField(default=0)),
                ('voucher_max_discount', models.PositiveIntegerField(default=0)),
                ('voucher_valid_days', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RewardVoucherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cost_points', models.PositiveIntegerField(default=100)),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_discount', models.PositiveIntegerField(default=0)),
                ('valid_days', models.PositiveSmallIntegerField(default=7)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.RunPython(seed_reward_configs, migrations.RunPython.noop),
    ]
