# Generated by Django 5.2.5 on 2026-02-27 13:46

from django.db import migrations, models


def seed_premium_box_rewards(apps, schema_editor):
    MysteryBoxRewardOption = apps.get_model("users", "MysteryBoxRewardOption")
    if MysteryBoxRewardOption.objects.filter(box_tier="PREMIUM").exists():
        return

    MysteryBoxRewardOption.objects.bulk_create([
        MysteryBoxRewardOption(
            name="Premium +150 điểm",
            box_tier="PREMIUM",
            reward_type="POINTS",
            points_value=150,
            weight=28,
            sort_order=101,
            active=True,
        ),
        MysteryBoxRewardOption(
            name="Premium +300 điểm",
            box_tier="PREMIUM",
            reward_type="POINTS",
            points_value=300,
            weight=16,
            sort_order=102,
            active=True,
        ),
        MysteryBoxRewardOption(
            name="Premium +3 lượt chơi",
            box_tier="PREMIUM",
            reward_type="PLAYS",
            plays_value=3,
            weight=15,
            sort_order=103,
            active=True,
        ),
        MysteryBoxRewardOption(
            name="Premium Voucher 10%",
            box_tier="PREMIUM",
            reward_type="VOUCHER",
            voucher_discount=10,
            voucher_max_discount=80000,
            voucher_valid_days=7,
            weight=8,
            sort_order=104,
            active=True,
        ),
        MysteryBoxRewardOption(
            name="Premium Voucher 15%",
            box_tier="PREMIUM",
            reward_type="VOUCHER",
            voucher_discount=15,
            voucher_max_discount=120000,
            voucher_valid_days=5,
            weight=4,
            sort_order=105,
            active=True,
        ),
        MysteryBoxRewardOption(
            name="Premium Chúc bạn may mắn lần sau",
            box_tier="PREMIUM",
            reward_type="EMPTY",
            weight=8,
            sort_order=106,
            active=True,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_mysteryboxrewardoption_rewardvoucheroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysteryboxrewardoption',
            name='box_tier',
            field=models.CharField(choices=[('STANDARD', 'Standard Box'), ('PREMIUM', 'Premium Box')], default='STANDARD', max_length=20),
        ),
        migrations.RunPython(seed_premium_box_rewards, migrations.RunPython.noop),
    ]
