# Generated by Django 5.2.5 on 2026-03-13 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0034_alter_order_payment_method'),
        ('users', '0012_alter_passwordresetotp_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Hoàn tiền vào ví'), ('PAYMENT', 'Thanh toán bằng ví')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='users_passw_email_b4e79e_idx',
            old_name='users_passw_email_f242fd_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='users_passw_user_id_45681c_idx',
            old_name='users_passw_user_id_f6a194_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='refund_wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refundwallettransaction',
            name='after_sales_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_wallet_transaction', to='shops.aftersalesrequest'),
        ),
        migrations.AddField(
            model_name='refundwallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_wallet_transactions', to='shops.order'),
        ),
        migrations.AddField(
            model_name='refundwallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
